/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package local.redes;

import java.io.IOException;

/**
 *
 * @author Marcelo Neves
 */
public class BatePapo extends javax.swing.JFrame {
    private java.net.MulticastSocket socket;
    private java.net.InetAddress enderecoGrupo;
    private int porta;
    private String usuario;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BatePapo.class.getName());

    /**
     * Creates new form BatePapo
     */
    public BatePapo() {
        initComponents();
        TfEndereco.setText("224.1.1.20");
        TfPorta.setText("50000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtConectar = new javax.swing.JButton();
        TfUsuario = new javax.swing.JTextField();
        TfEndereco = new javax.swing.JTextField();
        TfPorta = new javax.swing.JTextField();
        TfTexto = new javax.swing.JTextField();
        BtEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Endereco");

        jLabel3.setText("Porta");

        BtConectar.setText("Conectar");
        BtConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConectarActionPerformed(evt);
            }
        });

        TfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEnderecoActionPerformed(evt);
            }
        });

        BtEnviar.setText("Enviar");
        BtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEnviarActionPerformed(evt);
            }
        });

        TaTexto.setColumns(20);
        TaTexto.setRows(5);
        jScrollPane1.setViewportView(TaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(BtEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtConectar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtConectar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtEnviar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConectarActionPerformed
        // TODO add your handling code here:
        try {
            usuario = TfUsuario.getText();
            String ip = TfEndereco.getText();
            porta = Integer.parseInt(TfPorta.getText());

            if (usuario.trim().isEmpty()) {
                TaTexto.append("Por favor, informe um usuário.\n");
                return;
            }

            enderecoGrupo = java.net.InetAddress.getByName(ip);
            socket = new java.net.MulticastSocket(porta);
            socket.joinGroup(enderecoGrupo);

            Thread servidorRecepcao = new Thread(new Recebedor());
            servidorRecepcao.start();

            TaTexto.append("--- Conectado ao chat como " + usuario + " ---\n");

            BtConectar.setEnabled(false);
            TfEndereco.setEnabled(false);
            TfPorta.setEnabled(false);
            TfUsuario.setEnabled(false);

        } catch (Exception e) {
            TaTexto.append("Erro ao conectar: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_BtConectarActionPerformed

    private void BtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEnviarActionPerformed
        // TODO add your handling code here:
        try {
            String texto = TfTexto.getText();

            if (texto.equalsIgnoreCase("Sair")) {
                if (socket != null && !socket.isClosed()) {
                    socket.leaveGroup(enderecoGrupo);
                    socket.close();
                }
                System.exit(0);
            }

            if (!texto.trim().isEmpty()) {
                String mensagemCompleta = usuario + " diz: " + texto;
                byte[] msg = mensagemCompleta.getBytes();

                java.net.DatagramPacket dgPacket = new java.net.DatagramPacket(msg, msg.length, enderecoGrupo, porta);
                socket.send(dgPacket);

                TaTexto.append(mensagemCompleta + "\n");
                TfTexto.setText(""); 
            }

        } catch (IOException e) {
            TaTexto.append("Erro ao enviar: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_BtEnviarActionPerformed

    private void TfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BatePapo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConectar;
    private javax.swing.JButton BtEnviar;
    private javax.swing.JTextArea TaTexto;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfPorta;
    private javax.swing.JTextField TfTexto;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    class Recebedor implements Runnable {
        @Override
        public void run() {
            try {
                while (true) {
                    byte[] buffer = new byte[256];
                    java.net.DatagramPacket dgPacket = new java.net.DatagramPacket(buffer, buffer.length);

                    socket.receive(dgPacket);
                    String mensagem = new String(dgPacket.getData(), 0, dgPacket.getLength());

                    if (!mensagem.contains(usuario + " diz:")) {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            TaTexto.append(mensagem + "\n");
                        });
                    }
                }
            } catch (Exception e) {
                if (!socket.isClosed()) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        TaTexto.append("A conexão foi encerrada.\n");
                    });
                }
            }
        }
    }
}
