/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package local.redes;

/**
 *
 * @Marcelo Neves
 */
package local.redes;

import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import javax.swing.SwingUtilities;

import javax.swing.SwingUtilities;

import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.UnsupportedLookAndFeelException;

public class BatePapo extends javax.swing.JFrame {

    // Variáveis de Rede globais da classe
    private MulticastSocket socket;
    private InetAddress enderecoGrupo;
    private int porta;
    private String usuario;

    /**
     * Creates new form BatePapo
     */
    public BatePapo() {
        initComponents();
        // Pré-configurando com os dados obrigatórios do exercício
        TfEndereco.setText("224.1.1.20");
        TfPorta.setText("50000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfEndereco = new javax.swing.JTextField();
        TfPorta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtConectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaTexto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TfUsuario = new javax.swing.JTextField();
        BtEnviar = new javax.swing.JButton();
        TfTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHAT");
        setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Endereco");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Porta");

        BtConectar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BtConectar.setText("Conectar");
        BtConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConectarActionPerformed(evt);
            }
        });

        TaTexto.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        TaTexto.setColumns(20);
        TaTexto.setRows(5);
        TaTexto.setEnabled(false);
        jScrollPane1.setViewportView(TaTexto);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Usuário");

        BtEnviar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BtEnviar.setText("Enviar");
        BtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TfTexto)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(BtConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtConectar)
                                        .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtEnviar)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConectarActionPerformed
        try {
            usuario = TfUsuario.getText();
            String ip = TfEndereco.getText();
            porta = Integer.parseInt(TfPorta.getText());

            if (usuario.trim().isEmpty()) {
                TaTexto.append("Por favor, informe um usuário.\n");
                return;
            }

            // Inicializa conexão Multicast
            enderecoGrupo = InetAddress.getByName(ip);
            socket = new MulticastSocket(porta);
            socket.joinGroup(enderecoGrupo);

            // Inicia a Thread (Servidor) que ficará bloqueante aguardando mensagens
            Thread servidorRecepcao = new Thread(new Recebedor());
            servidorRecepcao.start();

            TaTexto.append("--- Conectado ao chat como " + usuario + " ---\n");

            // Bloqueia os campos de conexão para evitar cliques duplicados
            BtConectar.setEnabled(false);
            TfEndereco.setEnabled(false);
            TfPorta.setEnabled(false);
            TfUsuario.setEnabled(false);

        } catch (NumberFormatException e) {
            TaTexto.append("Erro ao conectar: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_BtConectarActionPerformed

    private void BtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEnviarActionPerformed
        try {
            String texto = TfTexto.getText();

            // Regra: Finalizar quando enviar "Sair"
            if (texto.equalsIgnoreCase("Sair")) {
                if (socket != null && !socket.isClosed()) {
                    socket.leaveGroup(enderecoGrupo);
                    socket.close();
                }
                System.exit(0);
            }

            if (!texto.trim().isEmpty()) {
                String mensagemCompleta = usuario + " diz: " + texto;
                byte[] msg = mensagemCompleta.getBytes();

                DatagramPacket dgPacket = new DatagramPacket(msg, msg.length, enderecoGrupo, porta);
                socket.send(dgPacket);

                // Como a thread receptora ignora as próprias mensagens (lógica do BatePapoOriginal),
                // escrevemos a nossa própria mensagem localmente na tela.
                TaTexto.append(mensagemCompleta + "\n");
                TfTexto.setText(""); // Limpa o campo após o envio
            }

        } catch (Exception e) {
            TaTexto.append("Erro ao enviar: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_BtEnviarActionPerformed

    /**
     * Classe Interna responsável por atuar como o SERVIDOR (Recebedor).
     * Roda em uma Thread separada e fica em estado bloqueante no socket.receive().
     */
    class Recebedor implements Runnable {
        @Override
        public void run() {
            try {
                while (true) {
                    byte[] buffer = new byte[256];
                    DatagramPacket dgPacket = new DatagramPacket(buffer, buffer.length);

                    // A thread pausa aqui (estado bloqueante) até uma mensagem chegar
                    socket.receive(dgPacket);

                    // Pega apenas o tamanho real da mensagem recebida para evitar lixo de memória no buffer
                    String mensagem = new String(dgPacket.getData(), 0, dgPacket.getLength());

                    // Ignora as próprias mensagens para não duplicar na tela
                    if (!mensagem.contains(usuario + " diz:")) {
                        // SwingUtilities.invokeLater é a melhor prática para atualizar a UI a partir de outra Thread
                        SwingUtilities.invokeLater(() -> {
                            TaTexto.append(mensagem + "\n");
                        });
                    }
                }
            } catch (Exception e) {
                // Se a exceção ocorrer porque o socket foi fechado no botão "Sair", ignoramos silenciosamente
                if (!socket.isClosed()) {
                    SwingUtilities.invokeLater(() -> {
                        TaTexto.append("A conexão foi encerrada.\n");
                    });
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BatePapo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConectar;
    private javax.swing.JButton BtEnviar;
    private javax.swing.JTextArea TaTexto;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfPorta;
    private javax.swing.JTextField TfTexto;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
